import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";

type CreateAuditLogInput = {
  actorAdminUserId?: string | null;
  action: string;
  targetType?: string | null;
  targetId?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  metadata?: Prisma.InputJsonValue;
};

export async function createAuditLog(input: CreateAuditLogInput) {
  await prisma.auditLog.create({
    data: {
      actorAdminUserId: input.actorAdminUserId ?? null,
      action: input.action,
      targetType: input.targetType ?? null,
      targetId: input.targetId ?? null,
      ipAddress: input.ipAddress ?? null,
      userAgent: input.userAgent ?? null,
      metadata: input.metadata,
    },
  });
}

export const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  POST_CREATED: "POST_CREATED",
  POST_UPDATED: "POST_UPDATED",
  DRAFT_SAVED: "DRAFT_SAVED",
  POST_SCHEDULED: "POST_SCHEDULED",
  POST_CANCELLED: "POST_CANCELLED",
  POST_RETURNED_TO_DRAFT: "POST_RETURNED_TO_DRAFT",
  POST_DELETED: "POST_DELETED",
  MEDIA_UPLOADED: "MEDIA_UPLOADED",
  MEDIA_VARIANTS_GENERATED: "MEDIA_VARIANTS_GENERATED",
  POST_MEDIA_CHANGED: "POST_MEDIA_CHANGED",
  POST_MEDIA_CLEARED: "POST_MEDIA_CLEARED",
  POST_CALENDAR_DATETIME_CHANGED: "POST_CALENDAR_DATETIME_CHANGED",
  POST_STATUS_CHANGED: "POST_STATUS_CHANGED",
  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  FACEBOOK_SETTINGS_UPDATED: "FACEBOOK_SETTINGS_UPDATED",
  FACEBOOK_CONNECT_STARTED: "FACEBOOK_CONNECT_STARTED",
  FACEBOOK_CONNECTED: "FACEBOOK_CONNECTED",
  FACEBOOK_DISCONNECTED: "FACEBOOK_DISCONNECTED",
  FACEBOOK_CONNECTION_TESTED: "FACEBOOK_CONNECTION_TESTED",
  FACEBOOK_CONNECTION_TEST_FAILED: "FACEBOOK_CONNECTION_TEST_FAILED",
  POST_PUBLISH_MANUAL_REQUESTED: "POST_PUBLISH_MANUAL_REQUESTED",
  POST_PUBLISH_RETRY_REQUESTED: "POST_PUBLISH_RETRY_REQUESTED",
  POST_PUBLISH_STARTED: "POST_PUBLISH_STARTED",
  POST_PUBLISH_SUCCEEDED: "POST_PUBLISH_SUCCEEDED",
  POST_PUBLISH_FAILED: "POST_PUBLISH_FAILED",
  POST_PUBLISH_SKIPPED: "POST_PUBLISH_SKIPPED",
  WORKER_RUN_COMPLETED: "WORKER_RUN_COMPLETED",
  WORKER_STUCK_PUBLISHING_RECOVERED: "WORKER_STUCK_PUBLISHING_RECOVERED",
  ACCOUNT_USERNAME_UPDATED: "ACCOUNT_USERNAME_UPDATED",
  ACCOUNT_EMAIL_UPDATED: "ACCOUNT_EMAIL_UPDATED",
  ACCOUNT_PASSWORD_CHANGED: "ACCOUNT_PASSWORD_CHANGED",
} as const;
