ALTER TABLE `MediaVariant`
  MODIFY `variantType` ENUM(
    'ORIGINAL',
    'GALLERY_THUMBNAIL',
    'GALLERY_PREVIEW',
    'FACEBOOK_FEED',
    'GOOGLE_BUSINESS_SAFE',
    'INSTAGRAM_FEED_PLACEHOLDER'
  ) NOT NULL;
